### ISSUE TITLE
difference between curl / libcurl

### ISSUE THREAD

**Issue by finanalyst** [CurtTilmes/raku-libcurl#28]
Not sure if this is a Raku module problem. See output from terminal below. Different responses to what I thought should be equivalent requests.

Please not how `curl -I` yields a reponse-code of 200, and via `libcurl` a response-code of 403.
```
 $ raku -MLibCurl::Easy -e 'LibCurl::Easy.new(:nobody,URL=>"https://tools.ietf.org/html/rfc3339").perform.response-code.say'
403
$ curl -I  https://tools.ietf.org/html/rfc3339
HTTP/1.1 200 OK
Date: Mon, 15 Mar 2021 12:10:53 GMT
Server: Apache/2.2.22 (Debian)
<snip>
```

I have so far not been able to discover using a websearch how to replicate `curl -I` using `libcurl`, though it does seem that `:nobody` is the right option. I have not tried to replicate using `libcurl` in another language.

However, `curl` and `libcurl` are supposed to be related.

**Comment by CurtTilmes** [comment]
`:nobody` is the right option to use `HEAD` instead of `GET` for HTTP.

Also add the `-v` option to `curl` and the `:verbose` option for `LibCurl` and you can see more of what is happening.  It looks like some sort of TLS/SSL negotiation problem.

I don't know enough about TLS/SSL to understand what the problem is or how to fix it.

**Comment by finanalyst** [comment]
Ok, I'm closing this issue as it's not really related to the Raku module. But I've not had much luck understanding the problem at root.
